"""
Re-generate pipeline.py from notebook.ipynb.

Mirrors the Build cell in notebook.ipynb — run either one.
"""
import json
import pathlib
import re


def build_pipeline(notebook_path="notebook.ipynb"):
    nb = json.loads(pathlib.Path(notebook_path).read_text())

    step_srcs, pipeline_src = [], None
    for cell in nb["cells"]:
        if cell["cell_type"] != "code":
            continue
        tags = cell.get("metadata", {}).get("tags", [])
        src = "".join(cell["source"])

        if "kfp_step" in tags:
            step_srcs.append(src)
        elif "kfp_pipeline" in tags:
            pipeline_src = src

    if not step_srcs:
        raise RuntimeError("No cells tagged 'kfp_step' found.")
    if pipeline_src is None:
        raise RuntimeError("No cell tagged 'kfp_pipeline' found.")

    names = [
        m.group(1)
        for s in step_srcs
        for m in [re.search(r"^def (\w+)\(", s, re.MULTILINE)]
        if m
    ]

    out  = "# Generated by notebook.ipynb — do not edit manually.\n"
    out += "# Re-run the Build cell (or scripts/build_pipeline.py) to regenerate.\n\n"
    out += "from kfp import dsl\n"
    out += "from kfp.dsl import Input, Output, Artifact\n\n\n"
    out += "\n\n\n".join(step_srcs)
    out += "\n\n\n"
    out += pipeline_src
    out += "\n"
    pathlib.Path("pipeline.py").write_text(out)
    print(f"Wrote pipeline.py — {len(names)} component(s): {', '.join(names)}")


if __name__ == "__main__":
    build_pipeline()
